-- ゲーム定義
CREATE TABLE GAME_DEFINITION (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SIZE INT NOT NULL,
    VERSION BIGINT NOT NULL,
    CONSTRAINT GAME_DEFINITION_PK PRIMARY KEY (ID)
);

-- セル定義
CREATE TABLE CELL_DEFINITION (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    GAME_DEFINITION_ID BIGINT,
    HORIZONTAL_POSITION INT,
    VERTICAL_POSITION INT,
    ALIVE SMALLINT NOT NULL,
    CONSTRAINT CELL_DEFINITION_PK PRIMARY KEY (ID),
    CONSTRAINT CELL_DEFINITION_UK1 UNIQUE (GAME_DEFINITION_ID, HORIZONTAL_POSITION, VERTICAL_POSITION),
    CONSTRAINT CELL_DEFINITION_FK1 FOREIGN KEY (GAME_DEFINITION_ID) REFERENCES GAME_DEFINITION (ID)
);

-- ゲーム
CREATE TABLE GAME (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    SIZE INT NOT NULL,
    CONSTRAINT GAME_PK PRIMARY KEY (ID)
);

-- セル
CREATE TABLE CELL (
    ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    GAME_ID BIGINT,
    HORIZONTAL_POSITION INT,
    VERTICAL_POSITION INT,
    ALIVE SMALLINT NOT NULL,
    CONSTRAINT CELL_PK PRIMARY KEY (ID),
    CONSTRAINT CELL_FK1 FOREIGN KEY (GAME_ID) REFERENCES GAME (ID),
    CONSTRAINT CELL_UK1 UNIQUE (GAME_ID, HORIZONTAL_POSITION, VERTICAL_POSITION)
);
